### PR TITLE
Fix example

### PR DESCRIPTION
**Pull request by hirschenberger**
Very nice work btw.

### CODE REVIEW

**Comment by autohuonw** [comment]
Thanks for the pull request, and welcome! You should hear from @huonw (or someone else) soon.

**Comment by huonw** [comment]
Oh, thanks, good catch! What a useless example it was before.

@autohuonw r+

**Comment by autohuonw** [comment]
:pushpin: Commit ef65ff6 has been approved by `huonw`

**Comment by autohuonw** [comment]
:hourglass: Testing commit ef65ff6 with merge 98255fd...

**Comment by autohuonw** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/huonw/simple_parallel/builds/57302223)

**Comment by autohuonw** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/huonw/simple_parallel/builds/57302221)

**Pull request merged**
