### PR TITLE
Tweak docs & readme.

### PR DESCRIPTION
**Pull request by huonw**

### CODE REVIEW

**Comment by autohuonw** [comment]
@huonw: no appropriate reviewer found, use r? to override

**Comment by huonw** [comment]
@autohuonw r+

**Comment by autohuonw** [comment]
~~[]() @autohuonw r=huonw 60f7455 []()~~

**Comment by autohuonw** [comment]
:hourglass: Testing commit 60f7455 with merge 193b98a...

**Comment by autohuonw** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/huonw/simple_parallel/builds/54810846)

**Pull request merged**
