### PR TITLE
Add another benchmark.

### PR DESCRIPTION
**Pull request by huonw**

### CODE REVIEW

**Comment by huonw** [comment]
@autohuonw r+

**Comment by autohuonw** [comment]
~~[]() @autohuonw r=huonw 53bf558 []()~~

**Comment by autohuonw** [comment]
:hourglass: Testing commit 53bf558 with merge a15c85f...

**Comment by huonw** [comment]
@autohuonw r-

**Comment by huonw** [comment]
@autohuonw r+

**Comment by autohuonw** [comment]
~~[]() @autohuonw r=huonw 53bf558 []()~~

**Comment by autohuonw** [comment]
:hourglass: Testing commit 53bf558 with merge 55d9310...

**Comment by autohuonw** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/huonw/simple_parallel/builds/54671232)

**Comment by huonw** [comment]
@autohuonw retry

**Comment by autohuonw** [comment]
:hourglass: Testing commit 53bf558 with merge 83be2db...

**Comment by autohuonw** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/huonw/simple_parallel/builds/54671606)

**Pull request merged**
