### PR TITLE
Fix typo in crate top-level documentation.

### PR DESCRIPTION
**Pull request by jimblandy**
Trivial fix: 'eke' for 'eek'.

### CODE REVIEW

**Comment by autohuonw** [comment]
Thanks for the pull request, and welcome! You should hear from @huonw (or someone else) soon.

**Comment by huonw** [comment]
@autohuonw r+

Whoops, thanks!

**Comment by autohuonw** [comment]
:pushpin: Commit 81de9ed has been approved by `huonw`

**Comment by autohuonw** [comment]
:hourglass: Testing commit 81de9ed with merge 7874da2...

**Comment by autohuonw** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/huonw/simple_parallel/builds/58539604)

**Pull request merged**
