### PR TITLE
Update to crossbeam 0.2

### LINKED ISSUE #9: upgrade to crossbeam 0.2

### PR DESCRIPTION
**Pull request by bluss**
Fixes #9

### CODE REVIEW

**Comment by autohuonw** [comment]
Thanks for the pull request, and welcome! You should hear from @huonw (or someone else) soon.

**Comment by bluss** [comment]
Ok, crossbeam does not support Rust 1.3. Pushed a commit to have us test with Rust 1.4 instead.

**Comment by sbeckeriv** [comment]
Commenting on this. crossbeam 0.1.6 now fails to build for me on rustc 1.10.0 (cfcb716cf 2016-07-03)

**Comment by ConnyOnny** [comment]
This PR is important! For my [project relying on this crate](https://github.com/ConnyOnny/sdfgen), I needed to fork this project for a one line diff (just changing the crossbeam version makes this crate compile again).

**Pull request closed without merging**
